### ISSUE TITLE
关于网页的logo与Icon

### ISSUE THREAD

**Issue by Jenway** [SDU-Application/sduapplication.github.io#1]
从 [这个链接](https://www.prnewswire.com/news-releases/shandong-university-celebrates-its-120th-anniversary-301403462.html) 中找到了本项目使用的 logo，
我稍微用 PS 扣了下图:
![SDU_Logo_origin ](https://user-images.githubusercontent.com/63341978/233770179-565bdd10-5c14-45c2-80e8-262a60cac244.png)
这个是文件大小更小的版本:
![SDU_Logo_medium](https://user-images.githubusercontent.com/63341978/233770220-34029f5f-ebe9-4cb4-9448-b601d0d35a1f.png)
这个是和现在手册图片大小一样的版本:
![SDU_Logo_smal](https://user-images.githubusercontent.com/63341978/233770366-daa91ec5-3c08-4335-b9fc-af2ad969a20a.png)
另：网页icon可以用[学校官网的icon](https://www.sdu.edu.cn//favicon.ico)

**Comment by json13245** [comment]
收到，已替换。
commit id: 14af32d5f196fa08e1945aca3d0c4dc2d1f2eec3
